/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package br.ulbra.view;

/**
 *
 * @author beeme
 */
public class FRMenu extends javax.swing.JFrame {

    /**
     * Creates new form FRMenu7
     */
    public FRMenu() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenu3 = new javax.swing.JMenu();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        MICad = new javax.swing.JMenu();
        MICadUsu = new javax.swing.JMenuItem();
        MICadue = new javax.swing.JMenuItem();
        MICadSair = new javax.swing.JMenuItem();
        MICon = new javax.swing.JMenu();
        MIConUsu = new javax.swing.JMenuItem();
        MIConue = new javax.swing.JMenuItem();
        MIAju = new javax.swing.JMenu();
        MIAjuSobre = new javax.swing.JMenuItem();

        jMenu3.setText("jMenu3");

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("[ULBRA]- Menu Principal");

        jPanel1.setBackground(new java.awt.Color(204, 204, 204));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/ulbra/img/logo.png"))); // NOI18N
        jLabel1.setText("jLabel1");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(209, 209, 209)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 251, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(179, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(150, 150, 150)
                .addComponent(jLabel1)
                .addContainerGap(143, Short.MAX_VALUE))
        );

        MICad.setText("Cadastros");

        MICadUsu.setText("Usuários");
        MICadUsu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MICadUsuActionPerformed(evt);
            }
        });
        MICad.add(MICadUsu);

        MICadue.setText("???");
        MICad.add(MICadue);

        MICadSair.setText("Sair");
        MICadSair.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MICadSairActionPerformed(evt);
            }
        });
        MICad.add(MICadSair);

        jMenuBar1.add(MICad);

        MICon.setText("Consultas");

        MIConUsu.setText("Usuários");
        MIConUsu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MIConUsuActionPerformed(evt);
            }
        });
        MICon.add(MIConUsu);

        MIConue.setText("???");
        MICon.add(MIConue);

        jMenuBar1.add(MICon);

        MIAju.setText("Ajuda");

        MIAjuSobre.setText("Sobre");
        MIAju.add(MIAjuSobre);

        jMenuBar1.add(MIAju);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 19, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void MICadUsuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MICadUsuActionPerformed
        new FRCadUsu().setVisible(true);
    }//GEN-LAST:event_MICadUsuActionPerformed

    private void MIConUsuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MIConUsuActionPerformed
        new FRConUsu().setVisible(true);
    }//GEN-LAST:event_MIConUsuActionPerformed

    private void MICadSairActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MICadSairActionPerformed
        this.dispose();
    }//GEN-LAST:event_MICadSairActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FRMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FRMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FRMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FRMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FRMenu().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenu MIAju;
    private javax.swing.JMenuItem MIAjuSobre;
    private javax.swing.JMenu MICad;
    private javax.swing.JMenuItem MICadSair;
    private javax.swing.JMenuItem MICadUsu;
    private javax.swing.JMenuItem MICadue;
    private javax.swing.JMenu MICon;
    private javax.swing.JMenuItem MIConUsu;
    private javax.swing.JMenuItem MIConue;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}
